# Generated by Django 3.1.7 on 2021-03-07 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('precscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='direction',
            field=models.CharField(choices=[('B', 'Before meals'), ('A', 'After meals')], default='B', max_length=1, verbose_name='direction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drug',
            name='dose_unit',
            field=models.CharField(choices=[('M', 'ml'), ('U', 'unit'), ('TS', 'table spoon'), ('T', 'tea spoon')], default='M', max_length=2, verbose_name='dose unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drug',
            name='duration_unit',
            field=models.CharField(choices=[('D', 'Days'), ('W', 'Weeks'), ('Y', 'Years')], default='D', max_length=1, verbose_name='duration unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drug',
            name='frequency',
            field=models.CharField(choices=[('IR', 'If required'), ('I', 'Immediately'), ('OD', 'Once a day'), ('TWD', 'Twie a day'), ('THD', 'Thrice a day')], default='I', max_length=3, verbose_name='frequency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drug',
            name='preparation',
            field=models.CharField(choices=[('T', 'Tab.'), ('C', 'Cap.'), ('I', 'Inj.'), ('D', 'Drops')], default='T', max_length=1, verbose_name='preparation'),
        ),
        migrations.AddField(
            model_name='drug',
            name='route',
            field=models.CharField(choices=[('T', 'Topical'), ('O', 'Oral'), ('R', 'Rectal'), ('V', 'Vaginal'), ('I', 'Inhalation')], default='T', max_length=1, verbose_name='route'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drug',
            name='strength_unit',
            field=models.CharField(choices=[('M', 'mg'), ('G', 'gm'), ('N', 'ng'), ('MC', 'mcg')], default='M', max_length=2, verbose_name='strength unit'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='dose',
            field=models.IntegerField(verbose_name='dose'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='durations',
            field=models.IntegerField(verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='strength',
            field=models.IntegerField(verbose_name='strength/power'),
        ),
        migrations.AlterField(
            model_name='precscription',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='user.doctor'),
        ),
        migrations.RemoveField(
            model_name='precscription',
            name='drug',
        ),
        migrations.AddField(
            model_name='precscription',
            name='drug',
            field=models.ManyToManyField(to='precscription.Drug'),
        ),
        migrations.AlterField(
            model_name='precscription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='user.patient'),
        ),
    ]
