# Generated by Django 3.1.7 on 2021-03-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precscription', '0003_precscription_otc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='direction',
            field=models.CharField(choices=[('Before meals', 'B'), ('After meals', 'A')], max_length=12, verbose_name='direction'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='dose_unit',
            field=models.CharField(choices=[('ml', 'M'), ('unit', 'U'), ('table spoon', 'TS'), ('tea spoon', 'T')], max_length=12, verbose_name='dose unit'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='duration_unit',
            field=models.CharField(choices=[('Days', 'D'), ('Weeks', 'W'), ('Years', 'Y')], max_length=10, verbose_name='duration unit'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='frequency',
            field=models.CharField(choices=[('If required', 'IR'), ('Immediately', 'I'), ('Once a day', 'OD'), ('Twie a day', 'TWD'), ('Thrice a day', 'THD')], max_length=12, verbose_name='frequency'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='preparation',
            field=models.CharField(choices=[('Tab.', 'T'), ('Cap.', 'C'), ('Inj.', 'I'), ('Drops', 'D')], default='T', max_length=5, verbose_name='preparation'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='route',
            field=models.CharField(choices=[('Topical', 'T'), ('Oral', 'O'), ('Rectal', 'R'), ('Vaginal', 'V'), ('Inhalation', 'I')], max_length=10, verbose_name='route'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='strength_unit',
            field=models.CharField(choices=[('mg', 'M'), ('gm', 'G'), ('ng', 'N'), ('mcg', 'MC')], default='M', max_length=3, verbose_name='strength unit'),
        ),
    ]
