# Generated by Django 3.1.7 on 2021-03-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precscription', '0004_auto_20210307_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='direction',
            field=models.CharField(choices=[('B', 'Before meals'), ('A', 'After meals')], max_length=1, verbose_name='direction'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='dose_unit',
            field=models.CharField(choices=[('M', 'ml'), ('U', 'unit'), ('TS', 'table spoon'), ('T', 'tea spoon')], max_length=2, verbose_name='dose unit'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='duration_unit',
            field=models.CharField(choices=[('D', 'Days'), ('W', 'Weeks'), ('Y', 'Years')], max_length=1, verbose_name='duration unit'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='frequency',
            field=models.CharField(choices=[('IR', 'If required'), ('I', 'Immediately'), ('OD', 'Once a day'), ('TWD', 'Twie a day'), ('THD', 'Thrice a day')], max_length=3, verbose_name='frequency'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='preparation',
            field=models.CharField(choices=[('T', 'Tab.'), ('C', 'Cap.'), ('I', 'Inj.'), ('D', 'Drops')], default='T', max_length=1, verbose_name='preparation'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='route',
            field=models.CharField(choices=[('T', 'Topical'), ('O', 'Oral'), ('R', 'Rectal'), ('V', 'Vaginal'), ('I', 'Inhalation')], max_length=1, verbose_name='route'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='strength_unit',
            field=models.CharField(choices=[('M', 'mg'), ('G', 'gm'), ('N', 'ng'), ('MC', 'mcg')], default='M', max_length=2, verbose_name='strength unit'),
        ),
    ]
