# Generated by Django 3.1.7 on 2021-03-08 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('precscription', '0009_auto_20210308_0905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='precscription',
            options={'verbose_name': 'precscription', 'verbose_name_plural': 'precscriptions'},
        ),
    ]
