# Generated by Django 3.1.7 on 2021-03-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='otc',
            field=models.CharField(default='covid', max_length=100, verbose_name='over the counter medicine'),
            preserve_default=False,
        ),
    ]
