# Generated by Django 3.1.7 on 2021-03-07 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_patient_otc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='otc',
        ),
    ]
